name: Compress and Release Mods

on:
  push:
    branches:
      - main

jobs:
  compress-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install zip and 7zip
      run: sudo apt-get update && sudo apt-get install -y zip p7zip-full

    - name: Download and Install rar
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://www.rarlab.com/rar/rarlinux-x64-701.tar.gz
        tar -zxvf rarlinux-x64-701.tar.gz
        sudo cp rar/rar /usr/local/bin/
        sudo cp rar/unrar /usr/local/bin/

    - name: Compress files into zip
      run: zip -r minecraft.zip config data mods resourcepacks shaderpacks options.txt servers.dat TrashSlotSaveState.json -x *.git* *.github* README.md

    - name: Compress files into rar
      run: rar a minecraft.rar config data mods resourcepacks shaderpacks options.txt servers.dat TrashSlotSaveState.json -x *.git* *.github* README.md

    - name: Compress files into 7z
      run: 7z a minecraft.7z config data mods resourcepacks shaderpacks options.txt servers.dat TrashSlotSaveState.json -xr\!*.git* -xr\!*.github* -xr\!README.md

    - name: Create Release
      id: create_release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
      with:
        tag_name: v2.0.${{ github.run_number }}
        release_name: Release v2.0.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (ZIP)
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./minecraft.zip
        asset_name: minecraft.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (RAR)
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./minecraft.rar
        asset_name: minecraft.rar
        asset_content_type: application/x-rar-compressed

    - name: Upload Release Asset (7Z)
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./minecraft.7z
        asset_name: minecraft.7z
        asset_content_type: application/x-7z-compressed

    - name: Remove compressed files
      run: rm minecraft.zip minecraft.rar minecraft.7z
